---
ports:
  - port: 3000
    onOpen: open-preview
    # The port is visible to allow sharing of the preview
    visibility: public

tasks:
  - name: "Vite"
    init: |
      yarn install
    command: |
      export HMR_HOST=`gp url 3000`
      yarn run dev

vscode:
  extensions:
    - svelte.svelte-vscode
    - fivethree.vscode-svelte-snippets
    - editorconfig.editorconfig
    - davidanson.vscode-markdownlint
    - bpruitt-goddard.mermaid-markdown-syntax-highlighting
    - esbenp.prettier-vscode
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
    - voorjaar.windicss-intellisense
