image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
    # The port is visible to allow sharing of the preview
    visibility: public

tasks:
  - name: "Vite"
    before: |
      brew install git-lfs
      git lfs install
      git lfs pull
    init: pnpm install
    command: |
      export HMR_HOST=`gp url 3000`
      pnpm run dev

vscode:
  extensions:
    - bpruitt-goddard.mermaid-markdown-syntax-highlighting
    - davidanson.vscode-markdownlint
    - eamodio.gitlens
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - fivethree.vscode-svelte-snippets
    - GitHub.copilot
    - github.vscode-pull-request-github
    - mhutchie.git-graph
    - streetsidesoftware.code-spell-checker-french
    - streetsidesoftware.code-spell-checker
    - svelte.svelte-vscode
    - tamasfe.even-better-toml
    - voorjaar.windicss-intellisense
