[build]
publish = "build/"


[[headers]]
for = "/_app/immutable/*"
[headers.values]
cache-control = '''
	public,
	max-age=2592000,
	stale-while-revalidate=7776000,
	immutable'''


[[headers]]
for = "/favicon*"
[headers.values]
cache-control = '''
	public,
	max-age=21600,
	stale-while-revalidate=604800'''


[[redirects]]
from   = "https://alexandre.prgm.dev/*"
status = 301
force  = true
to     = "https://prgm.dev/alexandre"
[[redirects]]
from   = "https://sebastien.prgm.dev/*"
status = 301
force  = true
to     = "https://prgm.dev/sebastien"
[[redirects]]
from   = "https://tristan.prgm.dev/*"
status = 301
force  = true
to     = "https://prgm.dev/tristan"

[[redirects]]
from   = "/*"
status = 200
to     = "200.html"
